# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Usaint_viewer_ios_sdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  # Pods for Usaint_viewer_ios_sdk

  target 'Usaint_viewer_ios_sdkTests' do
    # Pods for testing
  end

end
